name: task_spark
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.3.1
  font_awesome_flutter: ^10.8.0
  pocketbase: ^0.22.0
  icons_plus: ^5.0.0
  url_launcher: ^6.3.1
  lottie: ^3.3.1 # lottie 패키지 추가
  flutter_secure_storage: ^9.2.4
  awesome_dialog: ^3.2.1
  intl: ^0.20.2
  timezone: ^0.10.1
  ntp: ^2.0.0
  google_sign_in: ^6.1.5
  image_picker: ^1.1.2
  flutter_background_service: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
